library(data.table)
fi <- "household_power_consumption.txt"
dat <- fread(fi, header=T, sep=";",na.strings=c("?","NA"))
dat <- subset(dat, dat$Date == "1/2/2007" | dat$Date == "2/2/2007")
ti<-mapply(paste,dat$Date,dat$Time,sep=",")
ti <- lapply(ti,strptime,format="%d/%m/%Y,%H:%M:%S")
ti <- lapply(ti,as.POSIXct)
ti <-unlist(ti)
dat$Global_active_power <- as.numeric(dat$Global_active_power)
png("plot2.png")
plot(ti,dat$Global_active_power,type="n",xaxt="n",ylab="Global Active Power (kilowatt)",xlab="")
Axis(side=1,at=c(min(ti),mean(ti),max(ti)),labels=c("Thu","Fri","Sat"))
lines(ti,dat$Global_active_power)
dev.off()