library(data.table)
fi <- "household_power_consumption.txt"
dat <- fread(fi, header=T, sep=";",na.strings=c("?","NA"))
dat <- subset(dat, dat$Date == "1/2/2007" | dat$Date == "2/2/2007")
ti<-mapply(paste,dat$Date,dat$Time,sep=",")
ti <- lapply(ti,strptime,format="%d/%m/%Y,%H:%M:%S")
ti <- lapply(ti,as.POSIXct)
ti <-unlist(ti)
dat$Sub_metering_1 <- as.numeric(dat$Sub_metering_1)
dat$Sub_metering_2 <- as.numeric(dat$Sub_metering_2)
dat$Sub_metering_3 <- as.numeric(dat$Sub_metering_3)
png("plot3.png")
plot(ti,dat$Sub_metering_1,type="n",xaxt="n",ylab="Energy Sub Metering",xlab="")
Axis(side=1,at=c(min(ti),mean(ti),max(ti)),labels=c("Thu","Fri","Sat"))
lines(ti,dat$Sub_metering_1)
lines(ti,dat$Sub_metering_2,col="red")
lines(ti,dat$Sub_metering_3,col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"),lty=c(1,1,1),col=c("black","red","blue"))
dev.off()